name: The End of Celluloid
favicon: null
layout_spectrum: 0.6035342863760889
typography_spectrum: 0.4669070902746171
title: The End of Celluloid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.899348990758881
  lightness: 0.7292219002265483
  saturation: 0.24266517581418157
  rhythmicContrast: 0.33905498683452606
purpose: []
